### ISSUE TITLE
Eu acho que o endpoint está incorreto

### ISSUE THREAD

**Issue by jvictorfrancelino** [TiwWell/Farmacia-APIs#1]
O endpoint lista-cliente-string, deveria conter somente "lista-cliente", pois não retorna somente uma string... 
![Endpoint](https://github.com/TiwWell/Farmacia-APIs/assets/38146085/dd873d72-3686-458f-b8b3-4ec26972131d)

**Comment by TiwWell** [comment]
Compreensivel, tenha uma otima noite!
